doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: "%kernel.project_dir%/src/Entity"
        prefix: 'App\Entity'
        alias: App
fos_rest:
  body_converter:
    enabled: true
  view:
    formats: { json: true, xml: false, rss: false }
    view_response_listener: true
  serializer:
    serialize_null: true
  format_listener:
    rules:
        - { path: '^/', priorities: ['json'], fallback_format: 'json' }
sensio_framework_extra:
  view: { annotations: false } // éviter les collisions avec l'annotation  @View  du FOSRestBundle
